version: '0.1.0-ci.{build}'
init:
  - git config --global core.autocrlf input
branches:
  only:
    - master
build_script:
  - build.cmd
clone_depth: 1
test: off
artifacts:
  - path: 'artifacts\*.nupkg'
    name: nupkg
