<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="Product">
    <PackageVersion Include="AWSSDK.S3" Version="4.0.103.4" />
    <PackageVersion Include="AWSSDK.SecurityToken" Version="4.0.101" />
    <PackageVersion Include="AWSSDK.SSO" Version="4.0.100.16" />
    <PackageVersion Include="AWSSDK.SSOOIDC" Version="4.0.100.15" />
    <PackageVersion Include="Azure.Identity" Version="1.21.0" />
    <PackageVersion Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageVersion Include="DotNetConfig" Version="1.2.0" />
    <PackageVersion Include="McMaster.Extensions.CommandLineUtils" Version="5.1.0" />
    <PackageVersion Include="Microsoft.DiaSymReader.PortablePdb" Version="1.6.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="NuGet.Packaging" Version="7.9.0" />
    <PackageVersion Include="NuGet.Protocol" Version="7.9.0" />
  </ItemGroup>

  <ItemGroup Label="Analyzers">
    <PackageVersion Include="Roslynator.Analyzers" Version="5.0.0" />
    <PackageVersion Include="ToStringWithoutOverrideAnalyzer" Version="0.6.0" />
  </ItemGroup>

  <ItemGroup Label="Test">
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.HangDump" Version="2.4.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
    <PackageVersion Include="Moq" Version="4.21.0" />
    <PackageVersion Include="Moq.Analyzers" Version="0.4.2" />
    <PackageVersion Include="NuGet.Test.Helpers" Version="2.1.56" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.v3.assert" Version="4.0.1" />
    <PackageVersion Include="xunit.v3.extensibility.core" Version="4.0.1" />
  </ItemGroup>
</Project>
