<Project>
  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), 'README.md'))\build\test.props" />
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <!-- The build scripts set this to skip these tests. Run them with functional-tests.ps1 or functional-tests.sh -->
  <PropertyGroup Condition="'$(ExcludeFunctionalTests)' == 'true'">
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Protocol" />
    <PackageReference Include="NuGet.Test.Helpers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sleet.Test.Common\Sleet.Test.Common.csproj" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
