<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>Access Sleet.exe commands through the Sleet API.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591;1573</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="compiler\resources\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="AWSSDK.SecurityToken" />
    <PackageReference Include="AWSSDK.SSO" />
    <PackageReference Include="AWSSDK.SSOOIDC" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="DotNetConfig" />
    <PackageReference Include="Microsoft.DiaSymReader.PortablePdb" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NuGet.Packaging" />
  </ItemGroup>
</Project>
