<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetConfig" />
    <PackageReference Include="NuGet.Test.Helpers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sleet\Sleet.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Sleet.Test.Common\Sleet.Test.Common.csproj" />
  </ItemGroup>
</Project>
